### PR TITLE
minimum test including functional and state change

### PR DESCRIPTION
**Pull request by ctiml**
Story details: https://app.clubhouse.io/infuseai/story/6332

Add a basic controller test for ImageSpec

### CODE REVIEW

**Comment by jackklpan** [comment]
Question:
Another controller test example:
https://book.kubebuilder.io/reference/writing-tests.html
https://github.com/microsoft/azure-databricks-operator/blob/0f722a710fea06b86ecdccd9455336ca712bf775/controllers/suite_test.go
https://github.com/microsoft/azure-databricks-operator/blob/0f722a710fea06b86ecdccd9455336ca712bf775/controllers/workspaceitem_controller_test.go

They write one suite_test.go and share variables/settings between all controllers.
Our current structure will need every controller's tests to have their own instance of manager, k8sClient...etc.

Which might be the better structure for us?

**Comment by hSATAC** [comment]
Re: @jackklpan 
@ctiml and I discussed about this also, and we decided to go the separated controller tests.

The reasons are:
1. Our controllers are relatively independent. There's no need to bind all our controllers into one test suite.
2. Some of our controllers will interact with other controllers like `ImageJobController` & `ImageJobSpecController` we can combine these into the same controller test file, just like this PR.
3. In the long run, we think independent controller tests are easier to read and maintain. We don't want to see irrelevant details or variables of other controllers when we write tests.

Feel free to write your opinion if differ.

**Comment by jackklpan** [comment]
@hSATAC @ctiml 
I agree with the reasons especially the third point.

However, when I test(try) to write another controller test. I found that I cannot define:
```
var cfg *rest.Config
var k8sClient client.Client
var testEnv *envtest.Environment 
```
in global just like the image controller's test.
Because they have already defined in the image controller's test. 
The current structure may cause some problems for the other controller's tests.

**Comment by hSATAC** [comment]
@jackklpan Got it. I think we can fix that. Just a moment.

**Comment by hSATAC** [comment]
@jackklpan Done. We extracted the shared part into `suite_tests.go` but in the mean time every controller test file can write tests in their own `Context`

**Comment by jackklpan** [comment]
LGTM!

**Pull request merged**
