### PR TITLE
Feature/ch12294/implement artifacts copy logic

### PR DESCRIPTION
**Pull request by popcornylu**
** PR checklist **

- [x] Ensure you have added or ran the appropriate tests for your PR.
- [x] DCO signed

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
https://app.clubhouse.io/infuseai/story/12294/implement-artifacts-copy-logic

**Special notes for your reviewer**:
1. Sample configuration
```
jobSubmission:  graphqlEndpoint: https://hub.celu.aws.primehub.io/api/graphql
  phfsEnabled: true
  phfsPVC: primehub-store
  artifact:
    enabled: true
    limitSizeMb: 10
    limitFiles: 2
```
2. Manually apply the script configmap
```
cd <primehub-controller-repo>
kubectl -n hub create cm primehub-controller-job-scripts --from-file=run-job.sh=./ee/scripts/job/run-job.sh --dry-run=client -o yaml | kubectl apply -f -
```

3. Start the controlller. And submit a job with this command.
```
mkdir artifacts
date > artifacts/test.txt
```

4. file will be upload to `groups/<group>/jobArtifacts/<job-name>/`

Screenshot
image

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by popcornylu** [comment]
image: ch12294-bae49e5


and the chart PR is 
https://github.com/InfuseAI/primehub/pull/162

sample helm value.

```yaml
store:
  enabled: true
  phfs:
    enabled: true
jobSubmission:
  artifact:
    enabled: true
    limitSizeMb: 10
    limitFiles: 5
```

**Comment by popcornylu** [comment]
Test artifact too many files

commands
```
mkdir artifacts
for i in $(seq 0 100); do echo "hello" > artifacts/$i ; done
```

image

**Comment by popcornylu** [comment]
Test the artifact exceed the size limit

commands
```
echo "dump 5m"
mkdir artifacts
dd if=/dev/zero of=artifacts/test bs=5M count=1
```

image

**Comment by kentwelcome** [comment]
LGTM

**Pull request merged**
